#' Permutation Test for O-information
#'
#' Performs a permutation-based significance test for the
#' O-information of a candidate variable subset.
#'
#' This procedure corresponds to the first stage
#' of the hypergraph construction framework proposed by
#' Possenti et al. (2026).
#'
#' The null hypothesis assumes that the observed higher-order
#' dependency arises from chance. A null distribution is
#' generated by independently permuting each variable,
#' thereby preserving univariate distributions while
#' destroying multivariate dependence structure.
#'
#' The empirical p-value is computed as:
#'
#' \deqn{
#' p =
#' \frac{
#' \#(|\Omega_{perm}| \ge |\Omega_{obs}|)
#' }{
#' N_{perm}
#' }
#' }
#'
#' where \eqn{\Omega_{obs}} is the observed O-information
#' and \eqn{\Omega_{perm}} are values obtained from
#' permuted datasets.
#'
#' @param data Normalized data matrix or data frame.
#' @param vars Integer vector indicating variables belonging
#'   to the candidate multiplet.
#' @param n_perm Number of permutations.
#' @param cor_method Correlation method passed to
#'   \code{compute_correlation()}.
#'
#' @return A list containing:
#' \describe{
#'   \item{obs_O}{Observed O-information.}
#'   \item{pval}{Permutation p-value.}
#' }
#'
#' @references
#' Possenti, F., Girelli, L., Tieri, P., & Petti, M. (2026). Multiplex
#' Hypergraph Modeling of Higher Order Structures in Psychometric Networks
#' (Version 1). arXiv. https://doi.org/10.48550/ARXIV.2604.22744
#'
#' @export
permutation_Oinfo <- function(data, vars, n_perm = 1000, cor_method = "pearson") {
  data_sub <- data[, vars, drop = FALSE]
  obs_cor <- compute_correlation(data_sub, method = cor_method)
  obs_O <- compute_Oinfo(obs_cor)$Omega
  perm_O <- numeric(n_perm)
  for(i in seq_len(n_perm)) {
    data_perm <- as.data.frame(apply(data_sub, 2, sample))
    perm_cor <- compute_correlation(data_perm, method = cor_method)
    perm_O[i] <- compute_Oinfo(perm_cor)$Omega
  }
  pval <- mean(abs(perm_O) >= abs(obs_O))
  list(obs_O = obs_O, pval = pval)
}

#' BCa Bootstrap Validation for O-information
#'
#' Evaluates the robustness of a candidate hyperedge using
#' bias-corrected and accelerated (BCa) bootstrap confidence
#' intervals.
#'
#' This procedure corresponds to the second stage of the hypergraph construction
#'  framework proposed by Marinazzo et al. (2024) and adopted by
#' Possenti et al. (2026).
#'
#' Bootstrap samples are generated by resampling observations
#' with replacement. O-information is re-estimated for each
#' bootstrap sample and a BCa confidence interval is computed.
#'
#' A hyperedge is considered robust if its confidence interval
#' does not include zero.
#'
#' @param data Normalized data matrix or data frame.
#' @param vars Integer vector identifying variables in the
#'   candidate multiplet.
#' @param n_boot Number of bootstrap samples.
#' @param cor_method Correlation method passed to
#'   \code{compute_correlation()}.
#'
#' @return A list containing:
#' \describe{
#'   \item{ci_lower}{Lower BCa confidence limit.}
#'   \item{ci_upper}{Upper BCa confidence limit.}
#'   \item{robust}{Logical indicator whether the interval
#'   excludes zero.}
#' }
#'
#' @details
#' The BCa interval is preferred over standard percentile
#' intervals because it adjusts for both bias and skewness
#' in the bootstrap distribution.
#'
#' @references
#' Marinazzo, D., Van Roozendaal, J., Rosas, F. E., Stella, M.,
#' Comolatti, R., Colenbier, N., Stramaglia, S., & Rosseel, Y. (2024).
#' An information-theoretic approach to build hypergraphs in psychometrics.
#' *Behavior Research Methods*, *56*(7), 8057-8079.
#'
#' Possenti, F., Girelli, L., Tieri, P., & Petti, M. (2026). Multiplex
#' Hypergraph Modeling of Higher Order Structures in Psychometric Networks
#' (Version 1). arXiv. https://doi.org/10.48550/ARXIV.2604.22744
#'
#' @import boot
#' @export
bootstrap_Oinfo <- function(data, vars, n_boot = 1000, cor_method = "pearson") {
  boot_fun <- function(d, i) {
    cor_b <- compute_correlation(d[i, vars, drop = FALSE], method = cor_method)
    compute_Oinfo(cor_b)$Omega
  }
  boot_res <- boot::boot(data, boot_fun, R = n_boot)
  ci <- boot::boot.ci(boot_res, type = "bca")$bca[4:5]
  return(list(
    ci_lower = ci[1],
    ci_upper = ci[2],
    robust = !(ci[1] <= 0 & 0 <= ci[2])
  ))
}


#' Adjust P-values for Multiple Testing
#'
#' Applies multiple-testing correction to permutation-test
#' p-values.
#'
#' Currently supports false discovery rate (FDR) correction
#' and Holm's family-wise error rate correction.
#'
#' @param pvals Vector of raw p-values.
#' @param method Adjustment method ("fdr" and "holm").
#'
#' @return Vector of adjusted p-values.
#'
#' @seealso
#' \code{\link[stats]{p.adjust}}
multiple_test_correction <- function(pvals, method = c("fdr", "holm")) {
  method <- match.arg(method)
  if (method == "fdr") return(stats::p.adjust(pvals, "fdr"))
  if (method == "holm") return(stats::p.adjust(pvals, "holm"))
}

#' Check Confidence Interval Overlap
#'
#' Internal helper used in hierarchical validation.
#'
#' Determines whether two confidence intervals overlap.
#'
#' @keywords internal
#' @noRd
ci_overlap <- function(
    lower1,
    upper1,
    lower2,
    upper2
) {

  !(upper1 < lower2 || upper2 < lower1)
}

#' Hierarchical Validation of Candidate Hyperedges
#'
#' Performs hierarchical validation to determine whether a
#' significant higher-order interaction provides information
#' beyond its lower-order subsets.
#'
#' This procedure corresponds to the third stage of hypergraph construction
#'  framework proposed by Marinazzo et al. (2024) and adopted by
#' Possenti et al. (2026).
#'
#' For each robust k-order multiplet, the BCa confidence
#' interval of its O-information is compared against the
#' confidence intervals of all nested (k-1)-order subsets.
#'
#' If the confidence interval overlaps with any nested subset,
#' the higher-order interaction is considered non-informative
#' because its effect may be explained by lower-order
#' dependencies.
#'
#' Hyperedges that do not overlap with any nested subset are
#' considered hierarchically valid.
#'
#' @param results_df Data frame produced during the
#'   significance-testing pipeline.
#'
#' @return
#' The input data frame with an additional logical column:
#'
#' \describe{
#'   \item{hierarchical_valid}{
#'   Whether the hyperedge survives hierarchical validation.
#'   }
#' }
#'
#' @details
#' The rationale is that genuine higher-order interactions
#' should contribute information that cannot be fully
#' attributed to any lower-order component.
#'
#' Third-order multiplets are automatically considered
#' hierarchically valid because no lower-order hyperedges
#' exist in the framework.
#'
#' @references
#' Marinazzo, D., Van Roozendaal, J., Rosas, F. E., Stella, M.,
#' Comolatti, R., Colenbier, N., Stramaglia, S., & Rosseel, Y. (2024).
#' An information-theoretic approach to build hypergraphs in psychometrics.
#' *Behavior Research Methods*, *56*(7), 8057-8079.
#'
#' Possenti, F., Girelli, L., Tieri, P., & Petti, M. (2026). Multiplex
#' Hypergraph Modeling of Higher Order Structures in Psychometric Networks
#' (Version 1). arXiv. https://doi.org/10.48550/ARXIV.2604.22744
#'
#' @export
hierarchical_validation <- function(results_df) {
  results_df$hierarchical_valid <- FALSE
  var_lookup <- stats::setNames(seq_len(nrow(results_df)), results_df$vars)
  candidate_idx <- which(results_df$boot_robust)

  if(length(candidate_idx) == 0)
    return(results_df)

  for(i in candidate_idx){
    current_vars <- as.integer(strsplit(results_df$vars[i], "," )[[1]])
    current_k <- length(current_vars)

    if(current_k == 3){
      results_df$hierarchical_valid[i] <- TRUE
      next
    }

    current_lower <- results_df$boot_ci_lower[i]
    current_upper <- results_df$boot_ci_upper[i]
    overlap_found <- FALSE

    submultiplets <- utils::combn(
      current_vars,
      current_k - 1,
      simplify = FALSE
    )

    for(subset_vars in submultiplets){
      subset_name <- paste(sort(subset_vars), collapse = ",")
      subset_row <- var_lookup[[subset_name]]

      if(is.null(subset_row)) next

      if(is.na(results_df$boot_ci_lower[subset_row])) next

      overlap <- ci_overlap(
        current_lower,
        current_upper,
        results_df$boot_ci_lower[subset_row],
        results_df$boot_ci_upper[subset_row]
      )

      if(overlap){
        overlap_found <- TRUE
        break
      }
    }
    results_df$hierarchical_valid[i] <- !overlap_found
  }
  results_df
}

#' Three-Stage Significance Testing Pipeline for Hyperedges
#'
#' Performs the full inferential validation procedure for
#' candidate hyperedges following Possenti et al. (2026).
#'
#' The pipeline consists of three sequential stages:
#'
#' \enumerate{
#' \item Permutation testing against a null model (\code{\link{permutation_Oinfo}});
#' \item BCa bootstrap robustness assessment (\code{\link{bootstrap_Oinfo}});
#' \item Hierarchical validation against nested lower-order subsets (\code{\link{hierarchical_validation}}).
#' }
#'
#' Only hyperedges passing all three stages are retained as
#' statistically significant higher-order interactions.
#'
#' @param data Normalized data matrix or data frame.
#' @param multiplets List of candidate variable subsets.
#' @param n_perm Number of permutations.
#' @param n_boot Number of bootstrap samples.
#' @param alpha_perm Significance threshold after multiple
#' testing correction.
#' @param alpha_boot Reserved for future bootstrap-based
#' significance filtering.
#' @param Oinfo_threshold Minimum absolute O-information
#' required for bootstrap evaluation.
#' @param correct_method Multiple-testing correction method.
#' @param cor_method Correlation estimation method.
#' @param parallel Logical indicating whether parallel
#' processing should be used.
#' @param n_cores Number of worker processes.
#'
#' @return
#' A data frame containing:
#'
#' \describe{
#'   \item{hyperedge_id}{Hyperedge identifier.}
#'   \item{vars}{Variables composing the hyperedge.}
#'   \item{k}{Hyperedge order.}
#'   \item{Oinfo}{Observed O-information.}
#'   \item{perm_p}{Raw permutation p-value.}
#'   \item{perm_p_adj}{Adjusted p-value.}
#'   \item{boot_ci_lower}{Lower BCa confidence limit.}
#'   \item{boot_ci_upper}{Upper BCa confidence limit.}
#'   \item{boot_robust}{Bootstrap robustness indicator.}
#'   \item{hierarchical_valid}{Hierarchical validation result.}
#'   \item{significant}{Final significance indicator.}
#' }
#'
#' @details
#' This function implements the complete validation framework
#' described by Possenti et al. (2026) for psychometric
#' hypergraph construction.
#'
#' Candidate hyperedges are first screened against a
#' permutation-based null model. Surviving candidates are
#' then subjected to bootstrap robustness assessment.
#' Finally, hierarchical validation removes higher-order
#' interactions whose effects can be explained by nested
#' lower-order subsets.
#'
#' The resulting significant hyperedges constitute the final
#' hypergraph structure.
#'
#' @references
#' Marinazzo, D., Van Roozendaal, J., Rosas, F. E., Stella, M.,
#' Comolatti, R., Colenbier, N., Stramaglia, S., & Rosseel, Y. (2024).
#' An information-theoretic approach to build hypergraphs in psychometrics.
#' *Behavior Research Methods*, *56*(7), 8057-8079.
#'
#' Possenti, F., Girelli, L., Tieri, P., & Petti, M. (2026). Multiplex
#' Hypergraph Modeling of Higher Order Structures in Psychometric Networks
#' (Version 1). arXiv. https://doi.org/10.48550/ARXIV.2604.22744
#'
#' @seealso [permutation_Oinfo], [bootstrap_Oinfo], [hierarchical_validation]
#'
#' @export
sig_multiplet_testing_pipeline <- function(
    data,
    multiplets,
    n_perm = 1000,
    n_boot = 1000,
    alpha_perm = 0.05,
    alpha_boot = 0.05,
    Oinfo_threshold = 0.01,
    correct_method = c("fdr", "holm"),
    cor_method = c("pearson", "polychoric"),
    parallel = TRUE,
    n_cores = 1
) {
  n_mp <- length(multiplets)
  if (n_mp == 0) {
    warning("No multiplets to test.")
    return(data.frame())
  }
  correct_method <- match.arg(correct_method)
  cor_method <- match.arg(cor_method)

  res_df <- data.frame(
    hyperedge_id = 1:n_mp,
    vars = sapply(multiplets, function(x) paste(sort(x), collapse = ",")),
    k = sapply(multiplets, length),
    Oinfo = NA,
    perm_p = NA,
    perm_p_adj = NA,
    boot_ci_lower = NA,
    boot_ci_upper = NA,
    boot_robust = NA,
    hierarchical_valid = NA,
    significant = FALSE
  )

  # Step 1: Permutation testing
  message("Step 1/3: Running permutation tests (n = ", n_perm, ")...")
  future::plan(future::multisession, workers = n_cores)
  perm_results <- future.apply::future_lapply(
    multiplets,
    function(mp){
      psychHypergraph:::permutation_Oinfo(
        data = data,
        vars = mp,
        n_perm = n_perm,
        cor_method = cor_method
      )
    },
    future.seed = TRUE
  )

  for(i in seq_along(perm_results)){
    res_df$Oinfo[i] <- perm_results[[i]]$obs_O
    res_df$perm_p[i] <- perm_results[[i]]$pval
  }

  res_df$perm_p_adj <- multiple_test_correction(res_df$perm_p, correct_method)

  # Step 2: Bootstrap testing
  message("Step 2/3: Running BCa bootstrap validation (n = ", n_boot, ")...")
  sig_perm_idx <- which(res_df$perm_p_adj < alpha_perm & abs(res_df$Oinfo) >= Oinfo_threshold)

  boot_results <- future.apply::future_lapply(
    sig_perm_idx,
    function(i){
      psychHypergraph:::bootstrap_Oinfo(
        data = data,
        vars = multiplets[[i]],
        n_boot = n_boot,
        cor_method = cor_method
      )
    },
    future.seed = TRUE
  )

  for(j in seq_along(sig_perm_idx)){
    i <- sig_perm_idx[j]
    res_df$boot_ci_lower[i] <- boot_results[[j]]$ci_lower
    res_df$boot_ci_upper[i] <- boot_results[[j]]$ci_upper
    res_df$boot_robust[i] <- boot_results[[j]]$robust
  }

  # Step 3: Hierarchical validation
  message("Step 3/3: Running hierarchical validation...")
  res_df <- hierarchical_validation(res_df)

  # Final
  res_df$significant <- (
    res_df$perm_p_adj < alpha_perm &
      abs(res_df$Oinfo) >= Oinfo_threshold &
      res_df$boot_robust == TRUE &
      res_df$hierarchical_valid == TRUE
  )

  message("Completed: Found ", sum(res_df$significant), " significant hyperedges.")
  return(res_df)
}
